DATASETS:
  TRAIN: ("case_sensitive_sample_dataset_train",)
  TEST: ("new_sample_dataset_val",)
MODEL:
  WEIGHTS: "trained_models/pretrain/model_final.pth"
  META_ARCHITECTURE: "OneStageRCNN"
  ROI_HEADS:
    NAME: "TextHead"
    IOU_THRESHOLDS: [0.5]
  BATEXT:
    VOC_SIZE: 96
    NUM_CHARS: 25
    POOLER_RESOLUTION: (8, 32)
    POOLER_SCALES: (0.25,)
    SAMPLING_RATIO: 1
    CONV_DIM: 64
    NUM_CONV: 2
    RECOGNITION_LOSS: "ctc"
    CANONICAL_SIZE: 96  # largest min_size for level 3 (stride=8)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.001
  MAX_ITER: 40000
  CHECKPOINT_PERIOD: 5000
  CLIP_GRADIENTS:
    ENABLED: True
INPUT:
  HFLIP_TRAIN: False
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800, 832, 864, 896)
  MAX_SIZE_TRAIN: 1600
  MIN_SIZE_TEST: 1000
  MAX_SIZE_TEST: 1824
  CROP:
    ENABLED: True
    CROP_INSTANCE: False
    SIZE: [0.1, 0.1]
TEST:
  EVAL_PERIOD: 1000000
OUTPUT_DIR: "trained_models/finetune"
